### ISSUE TITLE
Update npm module

### ISSUE THREAD

**Issue by ivanovjaroslaw** [akserg/ng2-dnd#35]
Can you update this module: https://www.npmjs.com/package/ng2-dnd ?

And could you please provide the ability to use your repo via github url? What I mean. I try to use this in my package.json:
"ng2-dnd": "git+https://github.com/akserg/ng2-dnd.git#596c6a0"

But I got this error:
npm ERR! No version provided in package.json

Maybe you should just specify some version in your package.json?
Thanks!

**Comment by akserg** [comment]
Hi Jaroslav,

> Can you update this module: https://www.npmjs.com/package/ng2-dnd?

I changed the source of the library but didn't publish it yet, because it has some issues. May I ask you about the problem do you have with using the version available on [https://www.npmjs.com/package/ng2-dnd](https://www.npmjs.com/package/ng2-dnd)? 

> And could you please provide the ability to use your repo via GitHub URL?

I use the semantic versioning and [commetizen](http://commitizen.github.io/cz-cli/) helps me a lot to auto increment the version number of the project before publishing it into NPMJS. Please use the latest version from NPMJS or releases from https://github.com/akserg/ng2-dnd/releases.

**Comment by ivanovjaroslaw** [comment]
Hi, Sergey. I need the changes in this commit (about customization of dragImage): 596c6a0193a2547f687c5abf31d4b38d0a588e89
I see that this changes is only available in your repo. But I can't get them. I understand that you want to fix something before publishing into npmjs. But is there a way to get fresh code from your repo? As I said, just using this:
"ng2-dnd": "git+https://github.com/akserg/ng2-dnd.git#596c6a0"
And I got an error about 'npm ERR! No version provided in package.json'. If I want the last changes I should wait when you complete some fixes? Thanks!

**Comment by akserg** [comment]
Until I will check and publish the changes (ASAP) you can fork the project, make necessary changes and use in your project.

**Comment by ivanovjaroslaw** [comment]
I just think that it will be cool, if you specified version in package.json. So, some people, who want unstable version directly from github can get it (but at this time they can't because there is no 'version' prop in your package.json). I think you now that forking project is more complicated and inappropriate way. I think it's pretty good to give the developers some able for getting unstable fresh version. Thank you!
