### ISSUE TITLE
Getting the below error

### ISSUE THREAD

**Issue by sherry9872** [akserg/ng2-dnd#66]
ng2-dnd\src\abstract.component.d.ts(78,22): error TS1005: Build:'=' expected.
ng2-dnd\src\dnd.service.d.ts(19,14): error TS1005: Build:'=' expected.
ng2-dnd\src\dnd.service.d.ts(19,18): error TS1005: Build:';' expected.

**Comment by kjetilek** [comment]
@sherry9872 Have you tried upgrading to Typescript 2 (released recently)? I think these errors are caused by the use of "readonly" in the dnd-code - but it should go away if you use Typescript 2. Or you could just remove "readonly" in the specified lines to remove the error messages, this worked for me

**Comment by akserg** [comment]
Hi @sherry9872 
Did upgrade to Typescript 2 fixed your issue?

**Comment by AJMalik007** [comment]
@akserg @kjetilek  I am facing same issue and I updates typescript to 2 but issue not resolved so far

**Comment by sherry9872** [comment]
@akserg @kjetilek I have upgraded to angular 2 final and using typescript 2.0.3. still facing the same issue.

**Comment by akserg** [comment]
Hi @sherry9872 
Do you use SystemJS or Webpack? Would be nice to see the content of the package.json, tsconfig.json and typings.json files as well as the Application module. Did you include DndModule inside your application as described into [Import the DndModule](https://github.com/akserg/ng2-dnd#2-import-the-dndmodule)?
